<h2 class='lead'>Termenii si conditii DentistOnline</h2>
<p>In cele ce urmeaza va vom prezenta termenii si conditiile prin care site-ul DentistOnline.ro va pune la dispozitie serviciile sale de promovare online.</p>

<p class="article_details_title">1. Conditii de utilizare </p>
<div class="article_details"><p>DentistOnline.ro a stabilit o serie de reguli care trebuie respectate de toti cei care devin membri si utilizeaza serviciile noastre. Aceste conditii pot fi modificate , fara o anuntare prealabila a utilizatorilor. <!--Folosind serviciile oferite de catre Dentistonline, acceptati termenii si conditiile de mai jos si sunteti de acord ca acest lucru are valoarea unui contract, intre dumneavoastra si DentistOnline, acest document va obliga legal. -->Daca nu doriti sa respectati si sa indepliniti aceste conditii, va rugam sa nu folositi serviciile disponibile in cadrul site-ului.</p></div>

<p class="article_details_title">2. Servicii </p>
<div class="article_details"><p>Site-ul DentistOnline.ro ofera utilizatorilor informatii online din domeniul stomatologic si nu numai. Dvs. sunteti de acord ca aceste servicii includ si publicitate, anunturi, stiri, mesaje care sunt necesare site-ului DentistOnline.ro pentru o furnizarea cat mai complexa si bogata a serviciilor sale. Dvs. sunteti de acord cu serviciile site-ului, DentistOnline.ro nu isi asuma nici o responsabilitate pentru stergerea, transmiterea sau salvarea gresita a setarilor personalizate efectuate de dvs.</p></div>

<p class="article_details_title">3. Crearea unui nou cont - inregistrare</p>
<div class="article_details"><p>Pentrua beneficia de toate serviciile, facilitatile oferite de site trebuie sa va inregistrati si sunteti obligati sa:<br />
				3.1 oferiti date reale, exacte si complete despre dumneavoastra conform cerintelor din formularul de inregistrare.<br />
				3.2 mentineti si innoiti, atunci cand situatia o cere, datele de inregistrare pentru a fi adevarate, exacte si complete.<br />
		Daca informatiile primite nu sunt reale,sunt inexacte sau incomplete, DentistOnline are dreptul sa suspende sau sa desfiinteze contul dumneavoastra si sa refuze toate incercarile curente sau viitoare de folosire a site-ului.</p></div>

<p class="article_details_title">4. Dentistonline.ro protejarea informatiilor</p>
<div class="article_details"><p>DentistOnline.ro protejeaza informatiile primite dar putem oferi altor parti (numite terti) anumite informatii de ansamblu continute in formularul de inregistrare sau alte date de acelasi gen, asigurandu-va ca, aceste informatii nu vor cuprinde informatii personale de identificare, cu exceptia cazurilor cand acest lucru este acceptat explicit de dumneavoastra sau in cazul in care acest lucru este necesar pentru a respecta legea, procedurile judiciare, pentru a putea aplica aceste conditii de utilizare.</p>
			<p>Adresele dvs. de email nu vor fi facute publice si nici oferite altor parti, informatiile cu caracter grafic vor putea fi folosite in brosuri, pliante, newsletter, fluturasecreate special de dentistonline.ro, pentru promovarea dvs cat si a noastra.</p></div>

<p class="article_details_title">5. Responsabilitatile utilizatorului</p>
<div class="article_details"><p>Ca utilizator al site-ului sunteti responsabil de propriile actiuni precum si de consecintele pe care acestea le pot avea, in urma publicarii materialelor pe care le incarcati, puneti la dispozitie in mod public pe contul pus la dispozitie de companie. Sunt interzise uramtoarele:</p>
		<p>5.1 sa publicati material cu drept de autor, daca nu sunteti autorul sau daca nu aveti permisiunea autorului de a publica materialul respectiv;
		5.2 sa publicati materiale obscene, defaimatoare, de amenintare sau rauvoitoare fata de un alt utilizator, persoana fizica sau juridica;
		5.3 sa introduceti continut (imagini, text) rasist, explicit sexual, care provoaca la sadism, violenta sau fanatism religios;
		5.4 este interzisa proliferarea de mesaje calomnioase, de amenintare, vulgare, obscene, antisemite, cu tenta sexuala, rau intentionate, inexacte, sau care contravin, in orice fel, legii.
		5.5 sa publicati materiale care contin virusi, viermi sau alte programe cu intentia de a distruge orice sistem sau informatie;
		5.6 incarca, posta, difuza sau transmite in alt mod orice continut pentru care nu aveti dreptul legal de transmitere sau difuzare in orice conditii, sub orice sistem juridic, romanesc sau strain, relatii contractuale sau de incredere (cum sunt informatiile confidentiale, cele aflate sub drept de proprietate, aflate sau dezvaluite ca parte a relatiilor de serviciu sau aflate sub incidenta acordurilor de confidentialitate);
		5.7 promova sau furniza informatii despre modul de derulare a activitatilor ilegale, promova ranirea fizica sau verbala impotriva oricarui grup sau persoana, sau a promova orice act de cruzime fata de animale.</p>
		<p>DentistOnline.ro nu garanteaza credibilitatea, acuratetea informatiilor publicate de catre utilizatori si nu gireaza vreo parere exprimata de catre ei. DentistOnline.ro isi rezerva dreptul de a restrictiona folosirea site-lui anumitor utilizatori, daca acestia nu respecta termenii si conditiile siteu-lui .</p>
		<p>Atentie: sunteti in exclusivitate responsabili pentru continutul mesajelor dumneavoastra si veti suporta solidar consecintele acestora. DentistOnline.ro isi rezerva dreptul de a va declina calitatea de membru, din initiativa sa exclusiva, daca gaseste evident ca ati incalcat oricare din recomandari.
		DentistOnline.ro actioneaza ca un factor pasiv in distributia online si publicarea informatiilor furnizate de catre utilizatori si nu are obligatia de a verifica in avans materialele publicate de catre utilizatori. Daca i se solicita in mod expres de catre un utilizator, poate investiga si verifica datele si poate hotari daca informatiile respective trebuie indepartate sau daca trebuie restrictionat vreun utilizator. DentistOnline.ro isi poate asuma actiuni sau masuri in ceea ce priveste utilizatorii sau impotriva informatiilor inregistrate de catre acesia. Prin introducerea materialelor in orice segment public sau privat de pe site, garantati site-ului DentistOnline.ro dreptul continuu, irevocabil de a utiliza, reproduce, modifica, adapta, publica, traduce, distribui sau de a comunica in public continutul (in intregime sau partial), la scara internationala sau de a-l incorpora in alte lucrari de orice forma, in mass-media sau in tehnologia cunoscuta sau care urmeaza sa se dezvolte in viitor. De asemenea, permiteti oricarei persoane care este abonata sa acceseze, sa vizualizeze, sa stocheze informatiile. Supus celor mentionate, posesorul unui astfel de material publicat pe site isi mentine orice drepturi care ar putea deriva de aici. Apreciem mesajele tuturor utilizatorilor nostri si venim in intampinarea comentariilor dvs. cu privire la serviciile noastre. Va atentionam ca politica noastra nu ne permite sa acceptam sau sa tinem cont intotdeauna de ideile, sugestiile sau reclamatiile dvs.</p>
		<p>Sunteti consitient si accceptati ca mesajele primite dvs. sa fie verificate de catre administrator. Acesta pentru a opri primirea mesajelor spam.</>
		</div>

<p class="article_details_title">6. Informatii pentru utilizatori</p>
<div class="article_details"><p>In momentul in care va inregistrati pe site, vi se vor cere anumite informatii incluzand o adresa de e-mail valida. Prin completarea formularelor sunteti de accord ca datele dvs. sa intre in baza de date a DentistOnline.ro, aceste informatii pot fi folosite doar pentru promovarea unor produse sau servicii si acordati dreptul DentistOnline.ro de a va trimite periodic e-mail-uri cu informatii sau oferte speciale.</p></div>

<p class="article_details_title">7. Modificari ale serviciului</p>
<div class="article_details"><p>DentistOnline isi rezerva dreptul de a modifica in orice moment, sau la un anume interval de timp, sau sa intrerupa, temporar sau in mod permanent, serviciile puse la dispozitie (in totalitate sau numai in parte) cu sau fara o notificare prealabila. Sunteti de acord ca DentistOnline.ro nu este raspunzator fata de dumneavoastra sau orice terta persoana sau institutie pentru orice modificare, suspendare sau intrerupere a serviciilor disponibile prin intermediul site-lui.</p></div>

<p class="article_details_title">8. Incetarea colaborarii</p>
<div class="article_details"><p>Sunteti de acord ca DentistOnline.ro, daca considera de cuviinta, va poate bloca parola, utilizarea serviciilor sau folosirea oricaror altor servicii ale DentistOnline.ro de care beneficiati, sau sa scoata si sa stearga orice continut din cadrul serviciilor, pentru orice motiv, inclusiv dar nu limitat la, lipsa de folosire sau daca DentistOnline.ro considera ca ati violat sau nu ati actionat conform cu litera sau spiritul Regulilor de Utilizare. DentistOnline.ro poate deasemenea, oricand doreste si fara a da socoteala, intrerupe furnizarea serviciilor, sau a unei parti a lor, cu sau fara nici o notificare prealabila. Sunteti de acord ca orice incetare a accesului dumneavoastra la serviciile site-ului, conform oricarei reguli din Termene si Conditii, poate fi efectuata fara o avertizare anticipata, si/sau sa interzica orice acces ulterior la serviciile site-lui. Mai mult, sunteti de acord ca DentistOnline.ro nu va fi raspunzator fata de dumneavoastra sau orice terta parte in orice mod, pentru interzicerea si/sau stergerea contului si a accesului la serviciile puse la dispopzitie prin intermediul site-ului.</p></div>

<p class="article_details_title">9. Publicitate si promotii</p>
<div class="article_details"><p>DentistOnline.ro ruleaza campanii publicitare si promotii in cadrul siteului. O data cu crearea contului, acordati DentistOnline.ro dreptul de a rula astfel de campanii publicitare sau promotionale. Tipul, modul si marimea spatiului alocat pentru publicitate de catre DentistOnline.ro poate fi schimbat in orice moment cu sau fara notificare prealabila a utilizatorilor. Corespondenta sau afacerile sau participarea in promotii ale companiilor de publicitate gasite pe sau prin intermediul site-ului, inclusiv plati sau livrari ale unor bunuri sau servicii si orice alte conditii, termene, garantii sau reprezentari asociate cu astfel de relatii sunt numai in responsabilitatea dumneavoastra si a acestui tip de companii. Sunteti de acord ca DentistOnline.ro nu este raspunzator si nu va fi tras la raspundere pentru orice pierdere sau prejudiciu de orice fel, rezultat din astfel de relatii sau rezultat din prezenta unor astfel de companii in cadrul campaniilor publicitare ale site-ului.</p></div>

<p class="article_details_title">10. Legaturi catre alti furnizori de informatii sau servicii</p>
<div class="article_details"><p>Site-ul DentistOnline.ro poate furniza, sau terte parti pot furniza legaturi (link-uri) catre alte site-uri World Wide Web sau alte resurse. DentistOnline.ro isi rezerva dreptul de a nu accepta, de a restrictiona sau de a inceta folosirea Directorului Web inclus in site, a oricaror adrese ce nu corespund cu prezentul regulament.
Deoarece DentistOnline.ro nu are nici un control asupra acestor site-uri sau resurse, luati cunostinta si sunteti de acord ca DentistOnline.ro nu este responsabila de disponibilitatea acestora si nu garanteaza si nu este responsabila pentru nici un continut, publicitate, produse sau alte materiale de pe sau disponibile pe aceste site-uri sau resurse.
Mai mult, recunoasteti si sunteti de acord ca DentistOnline.ro nu va fi responsabila sau pasibila de a plati despagubiri, direct sau indirect pentru orice paguba sau pierdere cauzata sau presupusa a fi fost cauzata de sau in legatura cu folosirea sau increderea in informatiile furnizate de un asemenea continut, bunuri sau servicii disponibile pe sau prin intermediul unor astfel de site-uri sau resurse.</p></div>

<p class="article_details_title">11. Absolvirea de raspundere</p>
<div class="article_details"><p>Declarati in mod expres ca intelegeti si ca sunteti de acord cu urmatoarele afirmatii:
		11.1 utilizarea serviciilor site-ului se face pe propria raspundere. Serviciile sunt furnizate pe principiul "asa cum sunt" sau "asa cum sunt disponibile". DentistOnline.ro se absolva in mod expres de toate raspunderile de orice fel, exprimate direct sau indirect, inclusiv, dar nu limitat la garantiile indirecte de vanzare sau conformitate cu specificatiile pentru un anume scop.
		11.2 DentistOnline.ro nu ofera nici o garantie ca:
			11.2 utilizarea sau imposibilitatea utilizarii serviciilor site-urilor DentistOnline.ro
			11.2.2 serviciile vor implini toate cerintele dumneavoastra,
			11.2.3 serviciile vor fi neintrerupte, la timp, sigure sau fara erori,
			11.2.4 rezultatele ce se vor putea obtine din folosirea site-lui si a serviciilor puse la dispozitie vor fi corecte sau de incredere,
			11.2.5 calitatea oricaror produse, servicii, informatii sau alte materiale cumparate sau obtinute de dumneavoastra prin intermediul site-ului, va satisface toate cerintele, si
			11.2.6 orice eroare de program va fi corectata.
		11.3 Orice material descarcat sau obtinut in alt fel prin utilizarea serviciilor puse la dispozitie de DentistOnline.ro se afla astfel la discretia si poate fi folosit doar pe riscul propriu si veti singura persoana responsabila de eventualele distrugeri cauzate computerului de pe care accesati site-ului sau alte pierderi de date ce pot rezulta din descarcarea acestui tip de continut.
		11.4 Nici un sfat sau alte informatii orale sau scrise, obtinute de dumneavoastra de la DentistOnline.ro sau prin intermediul serviciilor noastre, va crea o garantie care nu este stipulata expres in Termene si Conditii.</p></div>

<p class="article_details_title">12. Responsabilitati DentistOnline.ro</p>
<div class="article_details"><p>Deoarece identificarea utilizatorilor pe Internet este dificila, DentistOnline.ro nu confirma faptul ca fiecare utilizator este ceea ce se pretinde. Deoarece nu suntem si nu putem fi implicati in relatiile user-to-user sau nu putem controla comportamentul utilizatorilor DentistOnline.ro, in eventualitatea unei dispute cu unul sau mai multi utilizatori, DentistOnline.ro este absolvita de orice raspundere sau despagubire (directa sau indirecta) de orice fel si de orice natura, cunoscuta sau necunoscuta, suspectata sau nu, dezvaluita sau nu, ivita in vreun mod care are legatura cu disputele. DentistOnline.ro nu are obligatia legala de a controla informatiile oferite de alti utilizatori, disponibile pe site. Informatiile altor persoane pot fi neplacute, vatamatoare sau inexacte. Materialul poate contine inexactitati sau greseli de scriere. DentistOnline.ro nu isi asuma veridicitatea si exactitatea materialului de pe site. Dvs.luati cunostinte si sunteti de acord cu faptul ca sunteti singurul responsabil pentru forma , continutul sau exactitatea materialului continut sau plasat de dvs pe site.</p></div>

<p class="article_details_title">13. Legea aplicabila</p>
<div class="article_details"><p>Legea aplicabila va fi legea romana, indiferent ca este vorba de legea penala sau de alta lege incidenta in problema respectiva.	Daca DentistOnline.ro va considera ca ati incalcat vreuna din conditiile stabilite in legatura cu site-ul, isi rezerva dreptul:
		13.1 sa va transmita un avertisment prin e-mail in legatura cu incalcarea conditiilor
		13.2 sa va stearga mesajele sau informatiile incorecte sau rauvoitoare de pe DentistOnline.ro
		13.3 sa va anuleze calitatea de membru al DentistOnline.ro
		13.4 sa faca plangere impotriva dumneavoastra la organele competente si/sau sa colaboreze cu acestea in cazul in care apar probleme care implica incalcarea vreunei legi.</p></div>

<p class="article_details_title">14. Incalcari</p>
<div class="article_details"><p>Daca ati observat ca aceste reguli din Termeni si Conditii nu sunt respectate, va rugam sa ne trimiteti un email la urmatoarea adresa: admin@dentistonline.ro si vom lua masurile de rigoare pentru rezolvarea problemelor.</p></div>